/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.jupiter.api.Test;

/** AppTest. */
public class AppTest {

    /**
     * determines whether the arr is sorted
     *
     * @param arr an array
     * @return whether the arr is sorted
     */
    static boolean isSorted(int[] arr) {
        if (arr.length == 0) {
            return true;
        }

        for (int i = 1; i < arr.length; i++) {
            if (arr[i] < arr[i - 1]) {
                return false;
            }
        }

        return true;
    }

    @Test
    void testEmptyArray() {
        int[] arr = {};
        App.sort(arr);
        assertTrue(isSorted(arr));
    }

    @Test
    void testSingleElementArray() {
        int[] arr = {0};
        App.sort(arr);
        assertTrue(isSorted(arr));
    }

    @Test
    void testAlreadySortedArray() {
        int[] arr = {1, 2, 3};
        App.sort(arr);
        assertTrue(isSorted(arr));
    }

    @Test
    void testReverseSortedArray() {
        int[] arr = {5, 4, 3, 2, 1};
        App.sort(arr);
        assertTrue(isSorted(arr));
    }

    @Test
    void testUnsortedArray() {
        int[] arr = {5, 4, 1, 2, 3};
        App.sort(arr);
        assertTrue(isSorted(arr));
    }

    @Test
    void testArrayWithDuplicates() {
        int[] arr = {3, 2, 4, 2, 3, 1};
        App.sort(arr);
        assertTrue(isSorted(arr));
    }

    @Test
    void testArrayWithNegativeNumbers() {
        int[] arr = {-2, -1, -3, 0, 1};
        App.sort(arr);
        assertTrue(isSorted(arr));
    }

    @Test
    void testPrintArrBasic() {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(baos);
        PrintStream old = System.out;
        System.setOut(ps);
        int[] arr = {1, 2, 3};
        App.printArr(arr);
        System.setOut(old);
        String cap = baos.toString();
        assertEquals("1 2 3", cap);
    }

    @Test
    void testPrintArrEmpty() {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(baos);
        PrintStream old = System.out;
        System.setOut(ps);
        int[] arr = {};
        App.printArr(arr);
        System.setOut(old);
        String cap = baos.toString();
        assertEquals("", cap);
    }

    @Test
    void testPrintArrOneElement() {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(baos);
        PrintStream old = System.out;
        System.setOut(ps);
        int[] arr = {1};
        App.printArr(arr);
        System.setOut(old);
        String cap = baos.toString();
        assertEquals("1", cap);
    }

    @Test
    void testMainMethod() {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream ps = new PrintStream(baos);
        PrintStream old = System.out;
        System.setOut(ps);
        App.main(new String[]{});
        System.setOut(old);
        String cap = baos.toString();
        assertEquals("1 2 3 4 5", cap);
    }
}
