/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] args) {
        String input = "3 + 2 * x";
        Expression e = Parser.parse(input);
        e.print();
        System.out.println("x=10: " + e.eval("x=10"));
        Expression de = e.derivative("x");
        de.print();
        de.simplify().print();
    }
}
