/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import java.util.Scanner;

/**
 * The main class of our App.
 */
public class App {
    /**
     * The main method of our app.
     *
     * @param args unused
     */
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        System.out.println("[WARN] gambling is addictive.");
        int roundCount = 1;
        int playerWins = 0;
        int dealerWins = 0;

        while (true) {
            System.out.printf("\nRound %d\n", roundCount);

            Game game = new Game();
            game.startRound();

            System.out.println(game.getHandStatusString());

            while (game.getState() == Game.GameState.PLAYER_TURN) {
                System.out.print("hit or stand? (h/s): ");
                String choice = input.next();

                if (choice.equalsIgnoreCase("h")) {
                    game.playerAction(Game.PlayerChoice.HIT);
                    System.out.println(game.getHandStatusString());

                } else if (choice.equalsIgnoreCase("s")) {
                    game.playerAction(Game.PlayerChoice.STAND);
                } else {
                    System.out.println("please enter 'h' or 's'.");
                }
            }

            if (game.getState() == Game.GameState.DEALER_TURN) {
                System.out.println("\nyou stand. dealer's turn...");
                game.dealerTurn();
                System.out.println(game.getHandStatusString());

            }

            System.out.printf("\n%s", game.getResultString());
            switch (game.getResult()) {
                case PLAYER_WIN:
                    playerWins += 1;
                    break;
                case DEALER_WIN:
                    dealerWins += 1;
                    break;
                default:
            }

            System.out.print("\nplay another round? (y/n): ");
            String playAgain = input.next();
            if (!playAgain.equalsIgnoreCase("y")) {
                break;
            }
            roundCount++;
        }

        System.out.printf("thanks for playing. score %d : %d", playerWins, dealerWins);
        input.close();
    }
}
